project/compiler/urls.py
from django.urls import path

from . import views


app_name = 'compiler'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('editor/<str:mode>', views.index, name='index'),
    # path('editor/<str:mode>/<int:file_pk>/', views.index, name='index'),
    path('editor/showfile/<int:file_pk>/', views.show_file, name='showfile'),
    path('showfile/<int:file_pk>/', views.show_file, name='showfile'),
    path('compile/<int:file_pk>/', views.compile_file, name='compile'),
    path('generate_file_tree_html/', views.generate_file_tree_html, name='generate_file_tree_html'),
    path('addFileForm/', views.generate_file_form_html, name="addFileForm"),
    path('addDirectoryForm/', views.generate_directory_form_html, name="addDirectoryForm"),
    path('delete_file/<int:file_pk>', views.delete_file, name='delete_file'),
    path('delete_directory/<int:dir_pk>', views.delete_directory, name='delete_directory'),
    path('', views.login_view, name='index'),
    path('logout/', views.logout_view, name='logout'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('compiler/', include('compiler.urls')),
    path('admin/', admin.site.urls),
]

project/compiler/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import User
# Create your models here.

class NamedEntity(models.Model):
    name = models.CharField(max_length=200)
    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class Directory(NamedEntity):
    # optional
    description = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # optional
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, verbose_name='parent directory')
    # Set to false on delete
    accesible = models.BooleanField(default=True)
    deleted_date = models.DateTimeField(null=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)

class File(NamedEntity):
    # optional
    description = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # optional
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE, null=True, blank=True)
    # Set to false on delete
    accesible = models.BooleanField(default=True)
    deleted_date = models.DateTimeField(null=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)

class SectionType(NamedEntity):
    can_be_nested = models.BooleanField(default=False)

class SectionStatus(NamedEntity):
    pass

class Section(models.Model):
    # optional
    name = models.CharField(max_length=200, blank=True)
    # optional
    description = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, verbose_name='parent section')
    begin = models.IntegerField(verbose_name='first row of section')
    end = models.IntegerField(verbose_name='last row of section')
    section_type = models.ForeignKey(SectionType, on_delete=models.PROTECT)
    status = models.ForeignKey(SectionStatus, on_delete=models.PROTECT)
    status_data = models.TextField(null=True, blank=True)
    body = models.TextField()

project/compiler/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    

project/compiler/views.py
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.shortcuts import render, redirect
from .models import *
from datetime import datetime
import subprocess
import tempfile
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
import os
import json
import re 

def get_flags_string(flags):
    if 'none' not in flags:
        return " ".join(str(x) for x in flags)
    return ""

class asmLine:
    def __init__(self, line, refCLine, section, isParent) -> None:
        self.line = line
        self.refCLine = refCLine
        self.section = section
        self.isParent = isParent

def process_asm(context, asm_code):
    asm_lines = asm_code.split('\n')
    context['asmLines'] = []
    current_C_line = 0
    current_section = 0
    for line in asm_lines:
        # check if line contains substring "/tmp/" and if it does,
        # extract first integer after ':' sign in line:
        if '/tmp/' in line:
            match = re.search(r'(?<=:)\d+', line)
            if match:
                current_C_line = int(match.group())
        # check if the preceeding line and the next line start with ;-
        # if they do, then the current line is a parent line

        preceeding_line = asm_lines[asm_lines.index(line) - 1]
        next_line = asm_lines[asm_lines.index(line) + 1]
        if preceeding_line.startswith(';-') and next_line.startswith(';-') and line.startswith(';'):
            current_section = current_section + 1
            context['asmLines'].append(asmLine(line, current_C_line, current_section, True))
        else:
            context['asmLines'].append(asmLine(line, current_C_line, current_section, False))
        # if line.startswith(';-') and asm_lines[asm_lines.index(line) + 1].startswith(';-'):
        #     current_section = current_section + 1
        #     context['asmLines'].append(asmLine(line, current_C_line, current_section, True))
        # else:
        #     context['asmLines'].append(asmLine(line, current_C_line, current_section, False))


def compile(context, request, file_pk):
    file_to_display = File.objects.get(pk=file_pk)
    sections = file_to_display.section_set.all().order_by('begin')
    temp_file = tempfile.NamedTemporaryFile(suffix='.c', delete=False)
    with open(temp_file.name, 'w') as f:
        for section in sections:
            f.write(section.body + '\n')
    
    if 'STD' not in request.session or 'PROC' not in request.session:
        context['fail'] = "Nie wybrano standardu C lub procesora"
        return
    c_standard = request.session['STD']
    procesor = request.session['PROC']
    procesor=procesor.lower()
    c_standard=c_standard.lower()
    if 'OPT' in request.session:
        opt_string = get_flags_string(request.session['OPT'])
    else:
        opt_string = ""
    if 'DEP' in request.session:
        dep_string = get_flags_string(request.session['DEP'])
    else:
        dep_string = ""


    try:
        if opt_string:
            if dep_string:
                subprocess.check_output(['sdcc', f'-m{procesor}','-S', opt_string, dep_string, f'--std-{c_standard}', temp_file.name], stderr=subprocess.STDOUT)
            else:
                subprocess.check_output(['sdcc', f'-m{procesor}','-S', opt_string, f'--std-{c_standard}', temp_file.name], stderr=subprocess.STDOUT)
        else:
            if dep_string:
                subprocess.check_output(['sdcc', f'-m{procesor}','-S', dep_string, f'--std-{c_standard}', temp_file.name], stderr=subprocess.STDOUT)
            else:
                subprocess.check_output(['sdcc', f'-m{procesor}','-S',  f'--std-{c_standard}', temp_file.name], stderr=subprocess.STDOUT)
        # return result.decode('utf-8')
    except subprocess.CalledProcessError as e:
        context['fail'] = e.output.decode('utf-8')
        return
    # Read and print the .asm file
    with open(temp_file.name[5:-2] + '.asm', 'r') as asm_file:
        asm_code = asm_file.read()
    # delete temp_file.name[5:-2] + '.asm' file
    subprocess.check_output(['rm', temp_file.name[5:-2] + '.asm'])
    process_asm(context, asm_code)

class Dir:
    def __init__(self, name, children, files, pk):
        self.name = name
        self.children = children
        self.files = files
        self.pk = pk

def get_file_layout(user):
    # get all parent directories and files without a parent directory
    parent_dirs = Directory.objects.filter(parent=None, accesible=True, owner=user)
    free_files = File.objects.filter(directory=None, accesible=True, owner=user)

    def generate_subtree(dir: Directory):
        children = Directory.objects.filter(parent=dir, accesible=True, owner=user)
        files = File.objects.filter(directory=dir, accesible=True, owner=user)
        children_list = []
        for child in children:
            children_list.append(generate_subtree(child))
        
        return Dir(dir.name, children_list, files, dir.pk)
    
    parent_dir_list = []

    for dir in parent_dirs:
        parent_dir_list.append(generate_subtree(dir))

    return {"parent_dir_list": parent_dir_list, "free_files": free_files}

def parse_file_to_sections(code, file: File):
    linesByNewLine = code.split('\n')
    lines = []
    for line in linesByNewLine:
        if line != '':
            lines.append(line)

    # Each nonempty line is a separate section:
    for i in range(len(lines)):
        section_type = SectionType.objects.get(name="other")
        section_status = SectionStatus.objects.get(name="default")
        section = Section(name="", description="", file=file, parent=None, begin=i,
                          end=i+1, section_type=section_type, status=section_status,
                          status_data="", body=lines[i])
        section.save()

def get_text_from_section(section: Section):
    # s_type = section.section_type
    # if (s_type.can_be_nested == False):
    return section.body + "\n"
    # else:
    #     sections = Section.objects.filter(parent=section).order_by('begin')
    #     text = ""
    #     for section in sections:
    #         text += get_text_from_section(section)
    #     return text

"""
mode: "show_file" or "add_file" or "add_dir"
file_pk: pk of file to show
"""
def index(request, mode='show_file', file_pk=None):
    if not request.user.is_authenticated:
        return redirect('/compiler/login')
    user = request.user
    
    context=get_file_layout(user)
    context['mode'] = mode
    context['file_pk'] = file_pk
    context['user'] = user

    # Handle Post requests:
    if request.method == 'POST':
        if 'STD' in request.POST:
            request.session['STD'] = request.POST['STD']
        if 'OPT' in request.POST:
            request.session['OPT'] = request.POST.getlist('OPT')
        if 'PROC' in request.POST:
            request.session['PROC'] = request.POST['PROC']
        if 'DEP' in request.POST:
            request.session['DEP'] = request.POST.getlist('DEP')

    # get session variables and save them to context:
    try:
        context['STD'] = request.session['STD']
    except:
        pass
    try:
        context['OPT'] = request.session['OPT']
    except:
        pass
    try:
        context['PROC'] = request.session['PROC']
    except:
        pass
    try:
        context['DEP'] = request.session['DEP']
    except:
        pass

    if (mode == 'add_file'):
        directories = Directory.objects.filter(accesible=True, owner=user)
        # user = CustomUser.objects.all()
        
        context['directories'] = directories

        if request.method == 'POST' and 'file' in request.FILES:
            filename = request.FILES['file'].name
            owner_pk = request.POST.get('owner_pk')
            
            directory_pk = request.POST.get('parent_directory_pk')
            if directory_pk == "":
                directory_pk = None
                directory = None
            else:
                try:
                    directory = Directory.objects.get(pk=directory_pk)
                except Directory.DoesNotExist:
                    context['failure'] = 'Folder nie istnieje'
                    return render(request, 'compiler/index.html', context)
            
            if directory_pk != None and Directory.objects.get(pk=directory_pk).owner != user:
                context['failure'] = 'Folder nie należy do właściciela'
                return render(request, 'compiler/index.html', context)
            
            # check if file already exists in directory:
            if (File.objects.filter(directory=directory, name=filename, accesible=True, owner=user).exists()):
                context['failure'] = 'Plik o podanej nazwie już istnieje w tym folderze'
                return render(request, 'compiler/index.html', context)
            
            description = request.POST.get('file_description')
            if description == None:
                description = ""

            file = File(name=filename, owner=user, directory=directory, description=description)
            file.save()
            parse_file_to_sections(request.FILES['file'].read().decode('utf-8'), file)

    elif (mode == 'add_dir'):
        # get all directories:
        directories = Directory.objects.filter(accesible=True, owner=user)
        context['directories'] = directories

        if request.method == 'POST':
            directory_name = request.POST.get('directory_name')
            parent_directory_pk = request.POST.get('parent_directory_pk')
            if (parent_directory_pk == ""):
                parent_directory = None
            else:
                try:
                    parent_directory = Directory.objects.get(pk=parent_directory_pk, owner=user)
                except Directory.DoesNotExist:
                    context['failure'] = 'Lokalizacja nie istnieje lub ma innego właściciela'

project/compiler/templates/compiler/add_dir.html
{% if success %}
<p>Folder dodany!</p>
{% endif %}

{% if failure %}
<p>Błąd: {{ failure }}</p>
<p>Spróbuj jeszcze raz!</p>
{% endif %}

<form action="{% url 'compiler:index' mode %}" method="post" enctype="multipart/form-data">
  
  {% csrf_token %}

  <!-- choose directory owner: -->
  <div>
    <label for='owner_pk'>Choose directory owner:</label>
    <select name="owner_pk" id="owner_pk">
      <option value="{{ user.pk }}">{{ user.username }}</option>
    </select>
  </div>
  
  <!-- choose parent directory: -->
  <div>
    <label for="parent_directory_pk">Choose parent directory:</label>
    <select name="parent_directory_pk" id="parent_directory_pk">
      {% for directory in directories %}
      <option value="{{ directory.pk }}">{{ directory.name }}</option>
      {% endfor %}
      <option value="">---</option>
    </select>
  </div>
  
  <!-- enter folder name: -->
  <div>
    <label for="directory_name">Enter folder name:</label>
    <input type="text" name="directory_name" id="directory_name">
  </div>
  
  <!-- Enter optional description, default is "" -->
  <div>
    <label for="directory_description">Enter folder description (optional):</label>
    <input type="text" name="directory_description" id="directory_description" value="">
  </div>
  <div class="submit">
    <button type="submit">Create</button>
  </div>
</form>

<div class="return">
  <button><a href="{% url 'compiler:index' %}">Home</a></button>
</div>

project/compiler/templates/compiler/add_directory.html
{% if success %}
<p>Folder dodany!</p>
{% endif %}

{% if failure %}
<p>Błąd: {{ failure }}</p>
<p>Spróbuj jeszcze raz!</p>
{% endif %}

<form action="{% url 'compiler:index' 'add_dir' %}" method="post" enctype="multipart/form-data">
  
  {% csrf_token %}

  <!-- choose directory owner: -->
  <div>
    <label for='owner_pk'>Choose directory owner:</label>
    <select name="owner_pk" id="owner_pk">
      <option value="{{ user.pk }}">{{ user.username }}</option>
    </select>
  </div>
  
  <!-- choose parent directory: -->
  <div>
    <label for="parent_directory_pk">Choose parent directory:</label>
    <select name="parent_directory_pk" id="parent_directory_pk">
      {% for directory in directories %}
      <option value="{{ directory.pk }}">{{ directory.name }}</option>
      {% endfor %}
      <option value="">---</option>
    </select>
  </div>
  
  <!-- enter folder name: -->
  <div>
    <label for="directory_name">Enter folder name:</label>
    <input type="text" name="directory_name" id="directory_name">
  </div>
  
  <!-- Enter optional description, default is "" -->
  <div>
    <label for="directory_description">Enter folder description (optional):</label>
    <input type="text" name="directory_description" id="directory_description" value="">
  </div>
  <div class="submit">
    <button type="submit">Create</button>
  </div>
</form>

project/compiler/templates/compiler/add_file.html
{% if success %}
  <p>Plik dodany!</p>
{% endif %}

{% if failure %}
  <p>Błąd: {{ failure }}</p>
  <p>Spróbuj jeszcze raz!</p>
{% endif %}

<form action="{% url 'compiler:index' 'add_file' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" name="file" accept=".c">
  
  <!-- choose directory owner: -->
  <div>
    <label for='owner_pk'>Właściciel:</label>
    <select name="owner_pk" id="owner_pk">
      <option value="{{ user.pk }}">{{ user.username }}</option>
    </select>
  </div>

  <!-- choose parent directory: -->
  <div>
    <label for="parent_directory_pk">Wybierz lokalizację:</label>
    <select name="parent_directory_pk" id="parent_directory_pk">
      {% for directory in directories %}
      <option value="{{ directory.pk }}">{{ directory.name }}</option>
      {% endfor %}
      <option value="">---</option>
    </select>
  </div>
  
  <!-- Enter optional description, default is "" -->
  <div>
    <label for="file_description">Opis (opcjonalny):</label>
    <input type="text" name="file_description" id="file_description" value="">
  </div>
  <input type="submit" value="Upload">
</form>

project/compiler/templates/compiler/files_view.html
<div class="sidebar-header">Witaj {{user.username}}!</div>
  <ul>
    {% for directory in parent_dir_list %}
    {% include "compiler/tree_view.html" %}
    {% endfor %}
  </ul>
  {% if free_files %}
    <!-- Print all files with hyperlinks -->
    {% for file in free_files %}
      <div class="file" id="{{ file.pk }}">
        <button onclick="showFile('{{file.pk}}')">{{file.name}}</button>
        <button onclick="deleteFile('{{file.pk}}')">Usuń</button>
      </div>
    {% endfor %}
  {% endif %}

project/compiler/templates/compiler/index.html
<!-- Autor: Jan Roguwski -->

{% load static %}

<!DOCTYPE html>
<html lang="pl">

<head>
  <title>online-C-compiler</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'compiler/styles.css' %}">
  <script src="{% static 'compiler/script.js' %}"></script>
</head>

<body class="light-mode">
  <div class="grid-container">
    <div class="topnav">
      <div class="nav-option" onclick="addFile()">
          Nowy Plik
      </div>
      <div class="nav-option" onclick="addDirectory()">
        Nowy Folder
      </div>
      <div class="nav-option"><a id='topnav-link' href="{% url 'compiler:logout' %}">Wyloguj się</a></div>
      <button onclick="toggleStyle()">Zmiana Trybu</button>

    </div>
    <div class="sidebar" id="sidebar">
      <div class="sidebar-header">Witaj {{user.username}}!</div>
      <ul>
        {% for directory in parent_dir_list %}
        {% include "compiler/tree_view.html" %}
        {% endfor %}
      </ul>
      {% if free_files %}
        <!-- Print all files with hyperlinks -->
        {% for file in free_files %}
          <div class="file" id="{{ file.pk }}">
            <button onclick="showFile('{{file.pk}}')">{{file.name}}</button>
            <button onclick="deleteFile('{{file.pk}}')">Usuń</button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <div class="main" id='main'>
      {% if mode == 'show_file' %}
        <pre>
          {% if source_code %}
{{ source_code }}
          {% endif %}
        </pre>
      {% endif %}
      
      {% if mode == 'add_file' %}
        {% include "compiler/add_file.html" %}
      {% endif %}
      
      {% if mode == 'add_dir' %}
        {% include "compiler/add_directory.html" %}
      {% endif %}
      
    </div>
    <div class="code" id="code">
      {% if result %}
        <pre>
{{ result }}
        </pre>
      {% endif %}
    </div>
    <div class="tabs">
      <div class="tabs-menu">
        <button class="tab_button" onclick="openTab(event, 'STD')">STANDARD</button>
        <button class="tab_button" onclick="openTab(event, 'OPT')">Optymalizacje</button>
        <button class="tab_button" onclick="openTab(event, 'PROC')">Procesor</button>
        <button class="tab_button" onclick="openTab(event, 'DEP')">Zależne</button>
      </div>
      <div id="STD"class="tabs-text">
        {% if STD %}
          <p>
            Aktualny standard: {{ STD }}
          </p>
        {% endif %}

        <form method="POST">
          {% csrf_token %}
          <select name="STD">
            <option value="c11">C11</option>
            <option value="c99">C99</option>
            <option value="c89">C89</option>
          </select>
          <input type="submit" value="Wybierz">
        </form>
      </div>
      <div id="OPT"class="tabs-text">
        {% if OPT %}
          <p>
            Wybrane optymalizacje: 
            {% for opt in OPT %}
              {{ opt }} 
            {% endfor %}
          </p>
        {% endif %}
        <form method="POST">
          {% csrf_token %}
          <input type="checkbox" name="OPT" value="--nogcse">--nogcse</input>
          <input type="checkbox" name="OPT" value="--noinvariant">--noinvariant</input>
          <input type="checkbox" name="OPT" value="--noinduction">--noinduction</input>
          <input type="checkbox" name="OPT" value="--noinvariant">--noinvariant</input>
          <input type="checkbox" name="OPT" value="--nojtbound">--nojtbound</input>
          <input type="checkbox" name="OPT" value="--noloopreverse">--noloopreverse</input>
          <input type="checkbox" name="OPT" value="none">brak</input>
          <input type="submit" value="Wybierz">
        </form>
      </div>
      <div id="PROC"class="tabs-text">
        {% if PROC %}
          <p>
            Aktualny procesor: {{ PROC }}
          </p>
        {% endif %}

        <form method="POST">
          {% csrf_token %}
          <select name="PROC">
            <option value="MCS51">MCS51</option>
            <option value="Z80">Z80</option>
            <option value="STM8">STM8</option>
          </select>
          <input type="submit" value="Wybierz">
        </form>
      </div>
      <div id="DEP"class="tabs-text">
        {% if PROC %}
          <p>
            Wybrane zależności dla procesora {{ PROC }}: 
            {% for dep in DEP %}
              {{ dep }} 
            {% endfor %}
          </p>
          <form method="POST">
            {% csrf_token %}
            {% if PROC == 'MCS51' %}
              <input type="checkbox" name="DEP" value="--model-small">--model-small</input>
              <input type="checkbox" name="DEP" value="--model-medium">--model-medium</input>
              <input type="checkbox" name="DEP" value="--model-large">--model-large</input>
              <input type="checkbox" name="DEP" value="--model-huge">--model-huge</input>
            {% endif %}
            {% if PROC == 'Z80' %}
              <input type="checkbox" name="DEP" value="--no-std-crt0">--no-std-crt0</input>
              <input type="checkbox" name="DEP" value="--callee-saves-bc">--callee-saves-bc</input>
              <input type="checkbox" name="DEP" value="--reserve-regs-iy">--reserve-regs-iy</input>
            {% endif %}
            {% if PROC == 'STM8' %}
              <input type="checkbox" name="DEP" value="--model-medium">--model-medium</input>
              <input type="checkbox" name="DEP" value="--model-large">--model-large</input>
            {% endif %}
              <input type="checkbox" name="DEP" value="none">brak</input>
            <input type="submit" value="Wybierz">
          </form>
        {% else %}
          <p>
            Wybierz procesor
          </p>
        {% endif %}
      </div>
    </div>
    
  </div>
</body>
</html>

project/compiler/templates/compiler/login.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'compiler/styles.css' %}">
</head>
<html lang="en">
    <div class="login">
        {% if logged_out %}
        <p> Wylogowano </p>
    {% endif %}
    <div class="form">
        <form method="post" class="login_form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </div>
    </div>

</html>

project/compiler/templates/compiler/show_asm.html
{% if fail %}
  <p>
    Błąd: {{ fail }}
  </p>
{% elif asmLines %}
  {% for line in asmLines %}
    <div class="amsLine" data-refCline="{{line.refCLine}}"
    data-section="{{line.section}}" data-isParent="{{line.isParent}}"
    onclick="highlightCCodeLine('{{line.refCLine}}' - 1, this)"
    ondblclick="collapseASMSection('{{line.section}}', '{{line.isParent}}')">
      <pre>{{ line.line }}</pre>
    </div>
  {% endfor %}
{% endif %}

project/compiler/templates/compiler/show_file.html
{% if sections %}
  {% for section in sections %}
    <pre class="C_line" id="l{{section.begin}}" >{{ section.body }}</pre>
  {% endfor %}
{% endif %}

project/compiler/templates/compiler/tree_view.html
<li>
    {{ directory.name }}
    <button onclick="deleteDirectory('{{directory.pk}}')">Usuń</button>
  {% if directory.children %}
  <ul>
    {% for child in directory.children %}
    {% with directory=child template_name="compiler/tree_view.html" %}
    {% include template_name %}
    {% endwith %}
    {% endfor %}
  </ul>
  {% endif %}
  {% if directory.files %}
    <!-- Print all files with hyperlinks -->
    {% for file in directory.files %}
      <div class="file" id="{{ file.pk }}">
        <button onclick="showFile('{{file.pk}}')">{{file.name}}</button>
        <button onclick="deleteFile('{{file.pk}}')">Usuń</button>
      </div>
    {% endfor %}
  {% endif %}
</li>